apiVersion: apps/v1
kind: Deployment
metadata:
  name: platecounter
  namespace: echoservice-ns
  labels:
    app: platecounter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platecounter
  template:
    metadata:
      labels:
        app: platecounter
    spec:
      containers:
        - name: platecounter-container
          image: platecounter:1.0-SNAPSHOT
          ports:
            - containerPort: 9090